// Define types for blog content sections
interface ContentSection {
  type: "text" | "image" | "video" | "quote";
  [key: string]: any;
}

interface TextSection extends ContentSection {
  type: "text";
  content: string;
}

interface ImageSection extends ContentSection {
  type: "image";
  src: string;
  alt: string;
  caption?: string;
}

interface VideoSection extends ContentSection {
  type: "video";
  videoId: string;
  caption?: string;
}

interface QuoteSection extends ContentSection {
  type: "quote";
  quote: string;
  author?: string;
}

// Type for a blog post
export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  datePublished: string;
  dateModified?: string;
  readingTime: number;
  authorName: string;
  authorAvatar: string;
  imageUrl: string;
  tags: string[];
  category: string;
  content: ContentSection[];
}

// Blog posts data
export const blogPostsData: BlogPost[] = [
  {
    id: "ferrari-ff-cooling-system",
    title: "Ferrari FF Cooling System Leakage Issues: Diagnosis and Solution",
    excerpt:
      "A Ferrari FF owner discovered red fluid in their garage - our systematic diagnosis revealed multiple coolant leaks caused by aluminum corrosion. Learn how we resolved this issue to prevent costly engine damage.",
    date: "April 4, 2025",
    datePublished: "2025-04-04T10:00:00+01:00",
    readingTime: 6,
    authorName: "Jason Playdon",
    authorAvatar: "/blog-images/jason-avatar.jpg",
    imageUrl: "/blog-images/ferrari-ff-thumbnail.jpg",
    tags: [
      "Ferrari",
      "FF",
      "Coolant Leak",
      "Cooling System",
      "Corrosion",
      "Maintenance",
      "V12",
    ],
    category: "Technical Repairs",
    content: [
      {
        type: "text",
        content:
          "Last week, a Ferrari FF owner approached us with a concerning issue. They had noticed a small amount of red fluid on their garage floor and initially feared it might be an oil leak. The vehicle was also showing signs of coolant loss, raising serious concerns about potential engine overheating.",
      },
      {
        type: "image",
        src: "/blog-images/ferrari-ff-front.jpg",
        alt: "Ferrari FF ready for coolant system diagnosis",
        caption:
          "The Ferrari FF in our workshop, ready for a comprehensive cooling system inspection",
      },
      {
        type: "text",
        content:
          "The Ferrari FF, with its sophisticated 6.3-liter V12 engine, relies on a complex cooling system to manage the substantial heat generated by this powertrain. Any compromise in this system can quickly lead to significant and costly engine damage if not addressed promptly.",
      },
      {
        type: "text",
        content:
          "Our diagnostic approach began with a careful inspection of the mysterious red fluid. We quickly determined it wasn't engine oil as the owner had initially feared, but rather coolant/antifreeze that had leaked from the vehicle. This explained the gradual loss of coolant the owner had been experiencing.",
      },
      {
        type: "quote",
        quote:
          "In high-performance vehicles like the Ferrari FF, even small leaks can indicate more significant underlying issues. What appears minor today can quickly develop into a critical problem that threatens engine integrity.",
        author: "Jason Playdon",
      },
      {
        type: "text",
        content:
          "To pinpoint the exact source of the leakage, we performed a comprehensive pressure test on the entire cooling system. This revealed multiple leak points stemming from various radiator hoses and coolant pipes throughout the system.",
      },
      {
        type: "image",
        src: "/blog-images/ferrari-ff-engine.jpg",
        alt: "Ferrari FF engine bay showing cooling system components",
        caption:
          "The complex array of coolant hoses and connections in the Ferrari FF's engine bay",
      },
      {
        type: "text",
        content:
          "Upon closer inspection, we identified aluminum corrosion on multiple connection points. This corrosion had compromised the sealing integrity between the aluminum components and rubber hoses, creating multiple small leak paths.",
      },
      {
        type: "text",
        content: "Our repair strategy was methodical and comprehensive:",
      },
      {
        type: "text",
        content:
          "1. We began by completely draining the cooling system to allow for a thorough inspection of all components.\n\n2. Each rubber hose was carefully removed and inspected for deterioration or damage.\n\n3. The critical aluminum connection points were meticulously cleaned to remove all traces of corrosion and restore proper sealing surfaces.\n\n4. All rubber hoses were reinstalled with appropriate torque to ensure proper sealing.",
      },
      {
        type: "video",
        videoId: "YOUR_VIDEO_ID_HERE",
        caption:
          "Jason demonstrating the proper cleaning technique for aluminum coolant fittings",
      },
      {
        type: "text",
        content:
          "During our inspection, we also noted that the coolant expansion tank cap showed signs of cross-threading, which could potentially compromise the system's ability to maintain proper pressure. We advised replacing this component to ensure the integrity of the entire cooling system.",
      },
      {
        type: "text",
        content:
          "With all connection points properly cleaned and reassembled, we refilled the system with fresh manufacturer-specified coolant. A follow-up pressure test confirmed that our repairs had completely resolved the leakage issues.",
      },
      {
        type: "image",
        src: "/blog-images/ferrari-ff-testing.jpg",
        alt: "Ferrari FF undergoing final testing",
        caption:
          "Final pressure testing of the cooling system to verify the repair's success",
      },
      {
        type: "text",
        content:
          "This case highlights several important considerations for Ferrari FF owners:",
      },
      {
        type: "text",
        content:
          "• Never ignore fluid leaks, no matter how small they may appear. Proper identification and prompt attention can prevent more extensive damage.\n\n• Cooling system maintenance is particularly critical in high-performance vehicles where operating temperatures are already near the upper limits of design parameters.\n\n• Aluminum corrosion in cooling systems is a common issue in vehicles of this caliber and should be addressed proactively during routine maintenance.",
      },
      {
        type: "text",
        content:
          "For Ferrari FF owners, we recommend the following preventive measures:",
      },
      {
        type: "text",
        content:
          "1. Schedule cooling system inspections every 2-3 years or 20,000 miles, even if no symptoms are present.\n\n2. Use only manufacturer-approved coolant with the correct additive packages to minimize corrosion.\n\n3. Consider a full cooling system flush and inspection if your vehicle is approaching 5 years of age or has been subjected to extended periods of non-use.\n\n4. Address any coolant loss immediately – even minor leaks can rapidly escalate into significant problems.",
      },
      {
        type: "quote",
        quote:
          "Preventive maintenance is always more cost-effective than reactive repairs, especially with vehicles of this caliber. A well-maintained Ferrari cooling system should provide years of trouble-free operation.",
        author: "Jason Playdon",
      },
      {
        type: "text",
        content:
          "If you've noticed coolant loss, fluid leaks, or temperature inconsistencies in your Ferrari or other high-performance vehicle, contact our specialist team at JP Performance Cars for a thorough diagnosis. With our extensive experience in Ferrari maintenance, we can identify and resolve these issues before they lead to costly repairs.",
      },
    ],
  },
  {
    id: "lamborghini-huracan-ecu-remapping",
    title: "Unlocking Hidden Performance: Lamborghini Huracán ECU Remapping",
    excerpt:
      "Explore how our precision ECU tuning delivered an additional 40bhp and improved drivability in a Lamborghini Huracán, while maintaining reliability.",
    date: "March 15, 2025",
    datePublished: "2025-03-15T14:30:00+01:00",
    readingTime: 5,
    authorName: "Jason Playdon",
    authorAvatar: "/blog-images/jason-avatar.jpg",
    imageUrl: "/blog-images/lamborghini-huracan.jpg",
    tags: [
      "Lamborghini",
      "Huracán",
      "Performance Tuning",
      "ECU Remapping",
      "V10",
    ],
    category: "Performance Upgrades",
    content: [
      {
        type: "text",
        content:
          "This is a placeholder for the Lamborghini Huracán ECU remapping article content. In a real implementation, this would contain detailed content about the process, results, and technical insights.",
      },
    ],
  },
  {
    id: "maserati-granturismo-carbon-ceramic-brake-maintenance",
    title:
      "Essential Maintenance for Maserati GranTurismo Carbon-Ceramic Brakes",
    excerpt:
      "Proper care and maintenance of carbon-ceramic brakes can extend their life and save thousands in replacement costs. Our guide for Maserati GranTurismo owners.",
    date: "February 22, 2025",
    datePublished: "2025-02-22T09:15:00+00:00",
    readingTime: 4,
    authorName: "Jason Playdon",
    authorAvatar: "/blog-images/jason-avatar.jpg",
    imageUrl: "/blog-images/maserati-granturismo.jpg",
    tags: [
      "Maserati",
      "GranTurismo",
      "Brakes",
      "Maintenance",
      "Carbon Ceramic",
    ],
    category: "Maintenance Tips",
    content: [
      {
        type: "text",
        content:
          "This is a placeholder for the Maserati GranTurismo brake maintenance article content. In a real implementation, this would contain detailed content about carbon-ceramic brake care.",
      },
    ],
  },
];
